# Generated by Django 3.0.5 on 2020-04-22 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0002_imagemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvseriesmodel',
            name='imdb_url',
            field=models.URLField(unique=True, verbose_name='IMDB page for the series'),
        ),
        migrations.AlterField(
            model_name='tvseriesmodel',
            name='series_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Name of the series'),
        ),
    ]
