# Generated by Django 3.0.5 on 2020-04-23 10:31

import archives.helpers.file_uploads
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0006_tvseriesmodel_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagemodel',
            options={'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='image',
            field=models.ImageField(upload_to=archives.helpers.file_uploads.save_image_path, verbose_name='An image'),
        ),
        migrations.AlterField(
            model_name='tvseriesmodel',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True, validators=[django.core.validators.MinValueValidator(limit_value=1, message='Zero is not a valid integer for this field')], verbose_name='Rating of TV series from 1 to 10'),
        ),
    ]
