# Generated by Django 3.0.5 on 2020-04-23 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0007_auto_20200423_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupingModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_for_interrelationship', models.TextField(null=True, verbose_name='Reason for relationship to an another series.')),
                ('series_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='archives.TvSeriesModel')),
                ('series_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='archives.TvSeriesModel')),
            ],
        ),
        migrations.AddField(
            model_name='tvseriesmodel',
            name='interrelationship',
            field=models.ManyToManyField(related_name='_tvseriesmodel_interrelationship_+', through='archives.GroupingModel', to='archives.TvSeriesModel'),
        ),
    ]
