# Generated by Django 3.0.5 on 2020-04-24 10:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0009_auto_20200423_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonmodel',
            name='number_of_episodes',
            field=models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(limit_value=1, message='Zero is not a valid integer for this field')], verbose_name='Number of episodes in the current season'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='groupingmodel',
            name='from_series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='archives.TvSeriesModel'),
        ),
    ]
