# Generated by Django 3.0.5 on 2020-04-24 11:18

import archives.helpers.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0010_auto_20200424_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasonmodel',
            name='last_watched_episode',
            field=models.PositiveSmallIntegerField(null=True, validators=[archives.helpers.validators.skip_if_none_none_zero_positive_validator], verbose_name='Last watched episode of a current season'),
        ),
    ]
