# Generated by Django 3.0.5 on 2020-04-24 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0011_auto_20200424_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasonmodel',
            name='last_watched_episode',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Last watched episode of a current season'),
        ),
    ]
