# Generated by Django 3.0.5 on 2020-04-26 06:54

import archives.helpers.validators
import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0013_auto_20200424_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasonmodel',
            name='episodes',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True, validators=[archives.helpers.validators.skip_if_none_none_zero_positive_validator], verbose_name='Episode number and issue date'),
        ),
        migrations.AlterField(
            model_name='seasonmodel',
            name='number_of_episodes',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1, message='Zero is not a valid integer for this field')], verbose_name='Number of episodes in the current season'),
        ),
    ]
