# Generated by Django 3.0.5 on 2020-04-26 13:24

import archives.helpers.validators
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0014_auto_20200426_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasonmodel',
            name='episodes',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True, validators=[archives.helpers.validators.validate_dict_key_is_digit, archives.helpers.validators.validate_timestamp], verbose_name='Episode number and issue date'),
        ),
        migrations.AddConstraint(
            model_name='seasonmodel',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('last_watched_episode__gte', 1), ('last_watched_episode__isnull', True), _connector='OR'), ('number_of_episodes__gte', 1)), name='last_watched_episode_and_number_of_episodes_are_gte_one'),
        ),
    ]
