# Generated by Django 3.0.5 on 2020-05-01 09:55

import archives.helpers.custom_fields
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0020_auto_20200501_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvseriesmodel',
            name='rating',
            field=archives.helpers.custom_fields.CustomPositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(limit_value=1, message='Zero is not a valid integer for this field')], verbose_name='Rating of TV series from 1 to 10'),
        ),
    ]
