# Generated by Django 3.0.5 on 2020-05-01 10:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0022_auto_20200501_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvseriesmodel',
            name='rating',
            field=models.SmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (None, 'No rating given')], null=True, validators=[django.core.validators.MinValueValidator(limit_value=1, message='Zero is not a valid integer for this field')], verbose_name='Rating of TV series from 1 to 10'),
        ),
    ]
