# Generated by Django 3.0.5 on 2020-05-02 11:52

import archives.helpers.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0024_auto_20200501_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvseriesmodel',
            name='imdb_url',
            field=models.URLField(unique=True, validators=[archives.helpers.validators.ValidateUrlDomain('www.imdb.com')], verbose_name='IMDB page for the series'),
        ),
    ]
