# Generated by Django 3.0.7 on 2020-06-05 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0032_auto_20200605_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupingmodel',
            name='to_series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_to', to='archives.TvSeriesModel'),
        ),
    ]
