# Generated by Django 3.0.7 on 2020-06-07 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0034_auto_20200607_1634'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groupingmodel',
            unique_together={('from_series', 'to_series')},
        ),
    ]
