# Generated by Django 3.0.7 on 2020-06-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0036_auto_20200615_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='image_hash',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Image hash.'),
        ),
    ]
