# Generated by Django 3.0.7 on 2020-06-15 17:20

import archives.helpers.custom_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0037_auto_20200615_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='image_hash',
            field=archives.helpers.custom_fields.ImageHashField(blank=True, max_length=50, null=True, verbose_name='Image hash.'),
        ),
    ]
