# Generated by Django 3.0.7 on 2020-06-20 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0040_auto_20200617_0924'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tvseriesmodel',
            options={'permissions': (('permissiveness', 'Allow any action'),), 'verbose_name': 'series', 'verbose_name_plural': 'series'},
        ),
    ]
