# Generated by Django 3.0.7 on 2020-06-27 14:31

import archives.helpers.validators
import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0042_auto_20200626_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvseriesmodel',
            name='translation_years',
            field=django.contrib.postgres.fields.ranges.DateRangeField(validators=[archives.helpers.validators.DateRangeValidator(upper_inf_allowed=True)], verbose_name='Series years of translation.'),
        ),
    ]
