# Generated by Django 3.0.7 on 2020-06-28 09:49

import datetime

import psycopg2.extras
from django.db import migrations, models

import archives.models


class Migration(migrations.Migration):
    db_table_name = archives.models.TvSeriesModel._meta.db_table
    model_name = archives.models.TvSeriesModel._meta.model_name
    constraint_name = 'defend_future_check'
    field_name = 'translation_years'

    dependencies = [
        ('archives', '0044_auto_20200627_2050'),
    ]

    operations = [
        migrations.RunSQL(sql=
                          f"""
                          alter table {db_table_name}
                            drop  CONSTRAINT if exists {constraint_name}
                            ;
                                  alter table {db_table_name}
                          add CONSTRAINT {constraint_name}
                            check (not {field_name} &&
                                daterange(
                                  (date_trunc('year', current_date) + interval '2 years')::date,
                                  NULL::date,
                                  '()'::text
                                ) or {field_name} @>
                                daterange(
                                  (date_trunc('year', current_date) + interval '2 years')::date,
                                  NULL::date,
                                  '()'::text))
                        ;
                            """
                          ,
                          reverse_sql=
                          f"""
                                  alter table {db_table_name}
                                    drop CONSTRAINT if exists {constraint_name}
                                    ;
                            """,
                          state_operations=[
                              migrations.AddConstraint(
                                  model_name=model_name,
                                  constraint=models.CheckConstraint(
                                      check=models.Q(
                                          _negated=True,
                                          translation_years__contained_by=
                                          psycopg2.extras.DateRange(datetime.date(2030, 1, 1), None, '()')),
                                      name=f'{constraint_name}'),

                              ), ])]
