# Generated by Django 3.0.7 on 2020-06-29 12:44

import archives.helpers.custom_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0045_defend_future_constraint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tvseriesmodel',
            name='is_finished',
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='image_hash',
            field=archives.helpers.custom_fields.ImageHashField(blank=True, max_length=16, null=True, unique=True, verbose_name='Image hash.'),
        ),
    ]
