# Generated by Django 3.0.8 on 2020-07-02 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0046_auto_20200629_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seasonmodel',
            name='episodes',
        ),
    ]
