# Generated by Django 3.0.8 on 2020-07-04 14:42

import django.contrib.postgres.constraints
from django.contrib.postgres.operations import BtreeGistExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0049_auto_20200704_1543'),
    ]

    operations = [
        BtreeGistExtension(),
        migrations.AddConstraint(
            model_name='seasonmodel',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(expressions=[('translation_years', '&&'), ('series', '=')], name='exclude_overlapping_seasons_translation_time_check'),
        ),
    ]
