# Generated by Django 3.0.8 on 2020-07-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0050_auto_20200704_1742'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='seasonmodel',
            name='season_number_gte_1_check',
        ),
        migrations.AddConstraint(
            model_name='seasonmodel',
            constraint=models.CheckConstraint(check=models.Q(season_number__range=(1, 30)), name='season_number_gte_1_check'),
        ),
    ]
