# Generated by Django 3.0.8 on 2020-07-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0051_auto_20200705_1638'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='seasonmodel',
            name='last_watched_episode_and_number_of_episodes_are_gte_one',
        ),
        migrations.AddConstraint(
            model_name='seasonmodel',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('last_watched_episode__gte', 1), ('last_watched_episode__isnull', True), _connector='OR'), ('number_of_episodes__range', (1, 30))), name='last_watched_episode_and_number_of_episodes_are_gte_one'),
        ),
    ]
