# Generated by Django 3.0.8 on 2020-07-07 14:52

import datetime

from django.db import migrations, models

import archives.models


class Migration(migrations.Migration):
    db_table_name = archives.models.SeasonModel._meta.db_table
    model_name = archives.models.SeasonModel._meta.model_name
    constraint_name = 'max_range_one_year'
    field_name = 'translation_years'

    dependencies = [
        ('archives', '0052_auto_20200705_2008'),
    ]

    operations = [
        migrations.RunSQL(sql=
                          f"""
                          alter table {db_table_name}
                            drop  CONSTRAINT if exists {constraint_name}
                            ;
                              alter table {db_table_name}
                              add CONSTRAINT {constraint_name}
                                check (
                                  upper({field_name}) - lower({field_name}) < 366
                                );
                            """
                          ,
                          reverse_sql=
                          f"""
                          alter table {db_table_name}
                            drop CONSTRAINT if exists {constraint_name};
                            """
                          ,
                          state_operations=[
                              migrations.AddConstraint(
                                  model_name=model_name,
                                  constraint=models.CheckConstraint(
                                      check=models.Q(translation_years__contained_by=datetime.timedelta(days=366)),
                                      name=constraint_name),
                              ), ])]

