# Generated by Django 3.0.8 on 2020-07-08 11:35

import django.contrib.postgres.indexes
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0053_max_range_one_year_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasonmodel',
            name='number_of_episodes',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1, message=('Zero is not a valid integer for this field.', 'zero_is_not_valid')), django.core.validators.MaxValueValidator(30)], verbose_name='Number of episodes in the current season'),
        ),
        migrations.AlterField(
            model_name='seasonmodel',
            name='season_number',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(limit_value=1, message=('Zero is not a valid integer for this field.', 'zero_is_not_valid')), django.core.validators.MaxValueValidator(30)], verbose_name='Number of the current season'),
        ),
        migrations.AddIndex(
            model_name='seasonmodel',
            index=django.contrib.postgres.indexes.GistIndex(fields=['translation_years'], name='archives_se_transla_a1d558_gist'),
        ),
        migrations.AddIndex(
            model_name='tvseriesmodel',
            index=django.contrib.postgres.indexes.GistIndex(fields=['translation_years'], name='archives_tv_transla_6917d6_gist'),
        ),
    ]
