# Generated by Django 3.0.8 on 2020-07-08 17:11

from django.db import migrations, models

import archives.models


class Migration(migrations.Migration):
    db_table_name = archives.models.SeasonModel._meta.db_table
    model_name = archives.models.SeasonModel._meta.model_name
    constraint_name = 'episodes_within_season_check'

    dependencies = [
        ('archives', '0055_hstore_constraint'),
    ]

    operations = [
        migrations.RunSQL(sql=
                          f"""
                              alter table {db_table_name}
                                drop  CONSTRAINT if exists {constraint_name}
                                ;
                                      alter table {db_table_name}
                              add CONSTRAINT {constraint_name}
                                check (
                                lower(translation_years) <= all(avals(episodes)::date[])
                                and upper(translation_years) >= all(avals(episodes)::date[])
                                )
                            ;
                                """
                          ,
                          reverse_sql=
                          f"""
                                      alter table {db_table_name}
                                        drop CONSTRAINT if exists {constraint_name}
                                        ;
                                """,
                          state_operations=[
                              migrations.AddConstraint(
                                  model_name=model_name,
                                  constraint=models.CheckConstraint(check=models.Q(('episodes__values__gte',
                                                                                    models.expressions.Func(
                                                                                        models.aggregates.Min(
                                                                                            models.expressions.F(
                                                                                                'translation_years')),
                                                                                        function='LOWER')), (
                                                                                   'episodes__values__lte',
                                                                                   models.expressions.Func(
                                                                                       models.aggregates.Max(
                                                                                           models.expressions.F(
                                                                                               'translation_years')),
                                                                                       function='UPPER'))),
                                                                    name=constraint_name),
                              ),

                               ])
    ]
