# Generated by Django 3.0.8 on 2020-07-13 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('archives', '0058_auto_20200712_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonmodel',
            name='entry_author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='seasons', to=settings.AUTH_USER_MODEL, verbose_name='Author of the season.'),
            preserve_default=False,
        ),
    ]
