# Generated by Django 3.0.8 on 2020-07-14 14:52

from django.contrib.auth.models import Group
from django.db import migrations

from series import constants


def apply_migration(apps, schema_editor):
    Group.objects.bulk_create([
        Group(name=constants.HANDLE_DELETED_USERS_GROUP), ],
        ignore_conflicts=True)


def revert_migration(apps, schema_editor):
    Group.objects.filter(
        name__in=[
            constants.HANDLE_DELETED_USERS_GROUP,
        ]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0059_seasonmodel_entry_author'),
    ]

    operations = [
        migrations.RunPython(apply_migration, revert_migration)
    ]
