# Generated by Django 3.0.8 on 2020-07-17 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0060_create_auth_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seasonmodel',
            options={'permissions': (('permissiveness', 'Allow any action'),), 'verbose_name': 'Season', 'verbose_name_plural': 'Seasons'},
        ),
    ]
