# Generated by Django 3.1 on 2020-08-05 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('archives', '0061_auto_20200717_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='entry_author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='images', to='users.user', verbose_name='Author of the image.'),
            preserve_default=False,
        ),
    ]
