# Generated by Django 3.1 on 2020-08-13 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0062_imagemodel_entry_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmptyTVSeriesModel',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('archives.tvseriesmodel',),
        ),
        migrations.AlterModelOptions(
            name='imagemodel',
            options={'permissions': (('permissiveness', 'Allow any action'),), 'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
    ]
