# Generated by Django 3.1.1 on 2020-09-08 07:55

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0069_fts_conf_check_function'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='subtitles',
            constraint=models.CheckConstraint(check=django.db.models.expressions.ExpressionWrapper(django.db.models.expressions.Func(django.db.models.expressions.F('search_configuration'), function='fts_conf_check'), output_field=models.BooleanField()), name='search_configuration_check'),
        ),
    ]
