# Generated by Django 3.1.1 on 2020-09-12 07:24

from django.contrib.postgres.operations import UnaccentExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0070_auto_20200908_1055'),
    ]

    operations = [
        UnaccentExtension(),
    ]
