# Generated by Django 3.0.6 on 2020-05-13 12:29

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200508_1534'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, master=django.db.models.expressions.F('pk')), name='point_on_itself_check'),
        ),
    ]
