# Generated by Django 3.0.6 on 2020-05-16 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userip'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='userip',
            index_together={('user', 'ip')},
        ),
    ]
