# Generated by Django 3.0.6 on 2020-05-20 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200517_1539'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userip',
            options={'get_latest_by': ('sample_time',), 'verbose_name': 'ip', 'verbose_name_plural': 'User ip addresses.'},
        ),
        migrations.AddField(
            model_name='user',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Is user account "deleted".'),
        ),
    ]
