# Generated by Django 3.0.6 on 2020-05-22 09:15

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200520_1727'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'default_manager_name': 'default', 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('default', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('first_name', 'last_name', 'email')},
        ),
    ]
