# Generated by Django 3.0.8 on 2020-07-14 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20200529_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deleted_time',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Time when user got soft-deleted'),
        ),
    ]
