# Generated by Django 3.1 on 2020-08-06 14:28

from django.db import migrations, models
import django.db.models.expressions
import users.database_functions


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_max_3_ips_function'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userip',
            constraint=models.CheckConstraint(check=users.database_functions.IpCount(django.db.models.expressions.F('user_id'), django.db.models.expressions.Value(3)), name='max_3_ips'),
        ),
    ]
