# Generated by Django 3.1 on 2020-08-07 12:49

from django.db import migrations


class Migration(migrations.Migration):
    function_name = 'json_diff'

    dependencies = [
        ('users', '0017_userip_trigger'),
    ]

    operations = [
        migrations.RunSQL(sql=
                          f"""
                            CREATE OR REPLACE FUNCTION {function_name}(left_json JSONB, right_json JSONB) RETURNS JSONB AS
                            $json_diff$
                                SELECT
                                    jsonb_object_agg(left_items.key, left_items.value)
                                 FROM
                                    ( SELECT key, value FROM jsonb_each(left_json) ) as left_items LEFT OUTER JOIN
                                    ( SELECT key, value FROM jsonb_each(right_json) ) as right_items using(key)
                                WHERE 
                                    left_items.value != right_items.value OR right_items.key IS NULL;
                            $json_diff$
                                LANGUAGE sql;
                               """
                          ,
                          reverse_sql=
                          f"""
                            drop function if exists {function_name}(v_user_id int, v_limit int);
                            """
                          ),
    ]
