# Generated by Django 3.0.5 on 2020-04-24 14:12

from django.db import migrations
from users.helpers.create_test_users import create_users, delete_users
from django.conf import settings
from django.contrib.auth import get_user_model


"""
This migration creates test set of user in database if settings DEBUG set to True.
"""


def forwards_func(apps, schema_editor):
    if settings.DEBUG and get_user_model().objects.exists():
        create_users()
    else:
        migrations.RunPython.noop(apps, schema_editor)


def reverse_func(apps, schema_editor):
    if settings.DEBUG and get_user_model().objects.exists():
        delete_users()
    else:
        migrations.RunPython.noop(apps, schema_editor)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_squashed_0005_auto_20200423_1739'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func)
    ]
