# Generated by Django 3.0.8 on 2020-07-26 13:11

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entrieschangelog',
            options={'get_latest_by': ('access_time',), 'verbose_name': 'Entries log', 'verbose_name_plural': 'Entries logs'},
        ),
        migrations.AddIndex(
            model_name='entrieschangelog',
            index=django.contrib.postgres.indexes.BrinIndex(autosummarize=True, fields=['access_time'], name='administrat_access__792fcf_brin'),
        ),
    ]
