# Generated by Django 3.0.8 on 2020-07-26 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_auto_20200726_1611'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='entrieschangelog',
            constraint=models.CheckConstraint(check=models.Q(as_who__in=['CREATOR', 'SLAVE', 'MASTER', 'FRIEND', 'ADMIN', 'LEGACY']), name='as_who_check'),
        ),
        migrations.AddConstraint(
            model_name='entrieschangelog',
            constraint=models.CheckConstraint(check=models.Q(operation_type__in=['CREATE', 'UPDATE', 'DELETE']), name='operation_type_check'),
        ),
    ]
