# Generated by Django 3.0.8 on 2020-07-29 17:22

import administration.encoders
import django.contrib.postgres.fields.jsonb
import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_entrieschangelog_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrieschangelog',
            name='state',
            field=django.contrib.postgres.fields.jsonb.JSONField(encoder=administration.encoders.CustomEncoder, verbose_name='Model state before save or delete.'),
        ),
        migrations.AddIndex(
            model_name='entrieschangelog',
            index=django.contrib.postgres.indexes.GinIndex(fields=['state'], name='administrat_state_f58034_gin'),
        ),
    ]
