# Generated by Django 3.0.8 on 2020-07-31 10:55

import django.contrib.postgres.constraints
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_auto_20200729_2022'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='entrieschangelog',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(operation_type__in=('DELETE', 'CREATE')), expressions=[('operation_type', '='), ('object_id', '='), ('content_type_id', '=')], name='multiple_delete_or_update_exclusion'),
        ),
    ]
