# Generated by Django 3.1 on 2020-08-21 10:31

import administration.encoders
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_auto_20200731_2015'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpBlacklist',
            fields=[
                ('ip', models.GenericIPAddressField(db_index=True, primary_key=True, serialize=False, unpack_ipv4=True, verbose_name='Ip address.')),
                ('record_time', models.DateTimeField(auto_now=True, verbose_name='Ip record time.')),
                ('stretch', models.DurationField(verbose_name='Time interval during which ip is blacklisted.')),
            ],
            options={
                'verbose_name': 'Ip blacklist.',
                'verbose_name_plural': 'Ip blacklists.',
                'get_latest_by': ('record_rime',),
            },
        ),
        migrations.AlterField(
            model_name='entrieschangelog',
            name='state',
            field=models.JSONField(encoder=administration.encoders.CustomEncoder, verbose_name='Model state before save or delete.'),
        ),
    ]
