# Generated by Django 3.1 on 2020-08-22 12:39

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0007_auto_20200821_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipblacklist',
            name='stretch',
            field=models.DurationField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.timedelta(0), message='The "stretch" field should be strictly positive.')], verbose_name='Time interval during which ip is blacklisted.'),
        ),
        migrations.AlterIndexTogether(
            name='ipblacklist',
            index_together={('record_time', 'stretch')},
        ),
    ]
