# Generated by Django 3.1 on 2020-08-21 11:24

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0007_auto_20200821_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipblacklist',
            name='stretch',
            field=models.DurationField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.timedelta(0))], verbose_name='Time interval during which ip is blacklisted.'),
        ),
        migrations.AddConstraint(
            model_name='ipblacklist',
            constraint=models.CheckConstraint(check=models.Q(stretch__gt=datetime.timedelta(0)), name='stretch_positive_check'),
        ),
    ]
