# Generated by Django 3.1 on 2020-08-30 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0009_auto_20200828_1353'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ipblacklist',
            constraint=models.CheckConstraint(check=models.Q(models.Q(models.Q(('ip__family', 4), ('ip__masklen__range', (24, 32))), models.Q(('ip__family', 6), ('ip__masklen__range', (120, 128))), _connector='OR')), name='netmask_check'),
        ),
    ]
