# Generated by Django 3.0.5 on 2020-04-21 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('first_name', 'last_name')},
        ),
        migrations.AlterIndexTogether(
            name='user',
            index_together={('first_name', 'last_name')},
        ),
    ]
