# Generated by Django 3.0.5 on 2020-04-23 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200421_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='slave',
            field=models.ForeignKey(db_index=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slaves', to=settings.AUTH_USER_MODEL, verbose_name='Slave account if not null'),
        ),
    ]
