# Generated by Django 3.0.5 on 2020-04-23 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_slave'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='slave',
            new_name='master',
        ),
    ]
