# Generated by Django 3.0.5 on 2020-04-22 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TvSeriesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_name', models.CharField(max_length=50, verbose_name='Name of the series')),
                ('imdb_url', models.URLField(verbose_name='IMDB page for the series')),
                ('entry_author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='series', to=settings.AUTH_USER_MODEL, verbose_name='Author of the series entry')),
            ],
        ),
        migrations.CreateModel(
            name='SeasonModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seasons', to='archives.TvSeriesModel', verbose_name='Parent TV series')),
            ],
        ),
    ]
