# Generated by Django 3.0.5 on 2020-04-22 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0003_auto_20200422_1226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tvseriesmodel',
            old_name='series_name',
            new_name='name',
        ),
    ]
