# Generated by Django 3.0.5 on 2020-04-22 17:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0004_auto_20200422_1555'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seasonmodel',
            options={'verbose_name': 'Season', 'verbose_name_plural': 'Seasons'},
        ),
        migrations.AlterModelOptions(
            name='tvseriesmodel',
            options={'verbose_name': 'series', 'verbose_name_plural': 'series'},
        ),
        migrations.AddField(
            model_name='seasonmodel',
            name='last_watched_episode',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(limit_value=1, message='Zero is not a valid integer for this field')], verbose_name='Last watched episode of a current season'),
        ),
        migrations.AddField(
            model_name='seasonmodel',
            name='season_number',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(limit_value=1, message='Zero is not a valid integer for this field')], verbose_name='Number of the current season'),
        ),
        migrations.AddField(
            model_name='tvseriesmodel',
            name='is_finished',
            field=models.BooleanField(default=False, verbose_name='Whether series finished or not'),
        ),
        migrations.AlterUniqueTogether(
            name='seasonmodel',
            unique_together={('series', 'season_number')},
        ),
        migrations.AlterIndexTogether(
            name='seasonmodel',
            index_together={('series', 'season_number')},
        ),
        migrations.AlterOrderWithRespectTo(
            name='seasonmodel',
            order_with_respect_to='series',
        ),
    ]
