# Generated by Django 3.0.5 on 2020-04-23 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0005_auto_20200422_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvseriesmodel',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True, verbose_name='Rating of TV series from 1 to 10'),
        ),
    ]
