# Generated by Django 3.0.5 on 2020-04-23 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0008_auto_20200423_2027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupingmodel',
            old_name='series_1',
            new_name='from_series',
        ),
        migrations.RenameField(
            model_name='groupingmodel',
            old_name='series_2',
            new_name='to_series',
        ),
    ]
