# Generated by Django 3.0.5 on 2020-04-27 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0015_auto_20200426_1624'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='tvseriesmodel',
            constraint=models.CheckConstraint(check=models.Q(('rating__range', (1, 11)), ('rating__isnull', True), _connector='OR'), name='rating_from_1_to_10'),
        ),
    ]
