# Generated by Django 3.0.5 on 2020-04-27 07:46

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0016_auto_20200427_0942'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='seasonmodel',
            constraint=models.CheckConstraint(check=models.Q(number_of_episodes__gte=django.db.models.expressions.F('last_watched_episode')), name='mutual_watched_episode_and_number_of_episodes_check'),
        ),
    ]
