# Generated by Django 3.0.5 on 2020-04-27 11:39

import archives.helpers.custom_fields
import archives.helpers.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0017_auto_20200427_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasonmodel',
            name='episodes',
            field=archives.helpers.custom_fields.CustomJSONField(null=True, validators=[archives.helpers.validators.validate_dict_key_is_digit, archives.helpers.validators.validate_timestamp], verbose_name='Episode number and issue date'),
        ),
        migrations.AddConstraint(
            model_name='seasonmodel',
            constraint=models.CheckConstraint(check=models.Q(season_number__gte=1), name='season_number_gte_1_check'),
        ),
    ]
