# Generated by Django 3.0.5 on 2020-05-01 09:30

import archives.helpers.custom_fields
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0019_auto_20200428_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvseriesmodel',
            name='rating',
            field=archives.helpers.custom_fields.CustomPositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True, validators=[django.core.validators.MinValueValidator(limit_value=1, message='Zero is not a valid integer for this field')], verbose_name='Rating of TV series from 1 to 10'),
        ),
    ]
