# Generated by Django 3.0.5 on 2020-05-01 10:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0021_auto_20200501_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvseriesmodel',
            name='rating',
            field=models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(limit_value=1, message='Zero is not a valid integer for this field')], verbose_name='Rating of TV series from 1 to 10'),
        ),
    ]
