# Generated by Django 3.0.5 on 2020-05-03 06:40

import archives.helpers.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0026_auto_20200502_1517'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tvseriesmodel',
            name='rating_from_1_to_10',
        ),
        migrations.AlterField(
            model_name='tvseriesmodel',
            name='imdb_url',
            field=models.URLField(unique=True, validators=[archives.helpers.validators.ValidateUrlDomain('www.imdb.com'), archives.helpers.validators.ValidateIfUrlIsAlive(3)], verbose_name='IMDB page for the series'),
        ),
        migrations.AlterField(
            model_name='tvseriesmodel',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (None, 'No rating given')], null=True, validators=[django.core.validators.MinValueValidator(limit_value=1, message='Zero is not a valid integer for this field'), django.core.validators.MaxValueValidator(limit_value=10, message='Maximal value for this field is 10')], verbose_name='Rating of TV series from 1 to 10'),
        ),
        migrations.AddConstraint(
            model_name='tvseriesmodel',
            constraint=models.CheckConstraint(check=models.Q(('rating__range', (1, 10)), ('rating__isnull', True), _connector='OR'), name='rating_from_1_to_10'),
        ),
    ]
