# Generated by Django 3.0.5 on 2020-05-04 10:49

import archives.helpers.validators
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0030_auto_20200504_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasonmodel',
            name='episodes',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, validators=[archives.helpers.validators.validate_dict_key_is_digit, archives.helpers.validators.validate_timestamp], verbose_name='Episode number and issue date'),
        ),
    ]
