# Generated by Django 3.0.7 on 2020-06-05 14:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0031_auto_20200504_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupingmodel',
            name='reason_for_interrelationship',
            field=models.TextField(default='just for fun', verbose_name='Reason for relationship to an another series.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seasonmodel',
            name='number_of_episodes',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1, message=('Zero is not a valid integer for this field.', 'zero_is_not_valid'))], verbose_name='Number of episodes in the current season'),
        ),
        migrations.AlterField(
            model_name='seasonmodel',
            name='season_number',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(limit_value=1, message=('Zero is not a valid integer for this field.', 'zero_is_not_valid'))], verbose_name='Number of the current season'),
        ),
        migrations.AlterField(
            model_name='tvseriesmodel',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (None, 'No rating given')], null=True, validators=[django.core.validators.MinValueValidator(limit_value=1, message=('Zero is not a valid integer for this field.', 'zero_is_not_valid')), django.core.validators.MaxValueValidator(limit_value=10, message='Maximal value for this field is 10')], verbose_name='Rating of TV series from 1 to 10'),
        ),
    ]
